MACRO CabriII vers. MS-Windows 1.0
Hipérbola envolvente, Esta hipérbola
Icon:
0000000000330000
0000000000330000
0000000000330000
0000000003300000
0000000003300000
0000000033000000
0000000330000000
0000033300000000
0333333000000000
0333300000000000
0000000000000000
0000000003330000
0000003333330000
0003333330003330
3333330000003330
3330000000000003
Mth: 0
CN:6, ON:56, FN:6, PO:55
CT:
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
Const:
Line, Mth:1, 0, 0, CN:2, VN:2, Const: 1 3
Biss, Mth:0, 0, 0, CN:3, VN:2, Const: 2 1 3
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 1 8
Biss, Mth:0, 0, 0, CN:3, VN:2, Const: 1 3 2
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 9 10
Line, Mth:1, 0, 0, CN:2, VN:2, Const: 2 3
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 11 12
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 12 13
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 3 10
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 9 15
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 16 12
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 12 17
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 2 12
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 4 2
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 6 20
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 2 21
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 4 2
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 5 23
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 2 24
Int, Mth:1, 0, 0, CN:2, VN:1, Const: 19 25
Seg, Mth:0, 0, 0, CN:2, VN:0, Const: 26 18
Int, Mth:1, 0, 0, CN:2, VN:1, Const: 19 22
Par, Mth:0, 0, 0, CN:2, VN:2, Const: 28 27
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 29 12
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 30 14
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 31 30
Int, Mth:1, 0, 256, CN:2, VN:1, Const: 19 32
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 2 1
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 33 34
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 1 35
Int, Mth:1, 0, 32768, CN:2, VN:1, Const: 8 36
Int, Mth:1, 1, 33024, CN:2, VN:1, Const: 8 36, B, W, t, DS:1 1, GT:1, I, nSt
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 38 8
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 39 7
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 1 40
Int, Mth:1, 0, 32768, CN:2, VN:1, Const: 8 41
Int, Mth:1, 0, 33024, CN:2, VN:1, Const: 8 41
Pt/, Mth:0, 0, 0, CN:1, VN:3, Const: 8
Pt/, Mth:0, 0, 0, CN:1, VN:3, Const: 8
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 38 43
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 44 46
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 43 47
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 37 42
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 44 49
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 42 50
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 38 43
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 45 52
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 43 53
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 37 42
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 45 55
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 42 56
Int, Mth:3, 1, 32896, CN:2, VN:1, Const: 48 51, R, W, t, DS:1 1, GT:1, I, nSt
Int, Mth:3, 1, 32897, CN:2, VN:1, Const: 48 51, R, W, t, DS:1 1, GT:1, I, nSt
Int, Mth:3, 1, 32896, CN:2, VN:1, Const: 57 54, R, W, t, DS:1 1, GT:1, I, nSt
Int, Mth:3, 1, 32897, CN:2, VN:1, Const: 57 54, R, W, t, DS:1 1, GT:1, I, nSt
Con, Mth:0, 1, 1, CN:5, VN:6, Const: 38 59 60 58 61, R, W, t, DS:1 1, GT:0, V, nSt
