MACRO CabriII vers. MS-Windows 1.0
Tangente desde los vértices, Esta tangente
Icon:
0000060000000000
0000060000000000
0000060000000000
0000006000000000
0000006000000066
0000006000000660
0000000600066000
0000000606660000
0000000660000000
0000006660000000
0000660060000000
0066000060000000
6600000006000000
0000000006000000
0000000006000000
0000000000600000
Mth: 0
CN:6, ON:46, FN:2, PO:45
CT:
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
point, CS 0, Bl, W, t, DS:1 1, GT:1, V, nSt
Const:
Line, Mth:1, 0, 0, CN:2, VN:2, Const: 1 3
Biss, Mth:0, 0, 0, CN:3, VN:2, Const: 2 1 3
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 1 8
Biss, Mth:0, 0, 0, CN:3, VN:2, Const: 1 3 2
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 9 10
Line, Mth:1, 0, 0, CN:2, VN:2, Const: 2 3
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 11 12
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 12 13
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 3 10
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 9 15
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 16 12
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 12 17
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 2 12
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 4 2
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 6 20
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 2 21
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 4 2
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 5 23
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 2 24
Int, Mth:1, 0, 0, CN:2, VN:1, Const: 19 25
Seg, Mth:0, 0, 0, CN:2, VN:0, Const: 26 18
Int, Mth:1, 0, 0, CN:2, VN:1, Const: 19 22
Par, Mth:0, 0, 0, CN:2, VN:2, Const: 28 27
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 29 12
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 30 14
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 31 30
Int, Mth:1, 0, 256, CN:2, VN:1, Const: 19 32
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 2 1
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 33 34
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 1 35
Int, Mth:1, 0, 32768, CN:2, VN:1, Const: 8 36
Int, Mth:1, 0, 33024, CN:2, VN:1, Const: 8 36
Perp, Mth:0, 0, 0, CN:2, VN:2, Const: 38 8
Int, Mth:0, 0, 0, CN:2, VN:1, Const: 39 7
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 1 40
Int, Mth:1, 0, 32768, CN:2, VN:1, Const: 8 41
Int, Mth:1, 0, 33024, CN:2, VN:1, Const: 8 41
Mid, Mth:0, 0, 0, CN:2, VN:1, Const: 37 42
Sym, Mth:0, 0, 0, CN:2, VN:1, Const: 38 44
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 42 45
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 2 43
Int, Mth:3, 0, 1, CN:2, VN:1, Const: 46 47
PBiss, Mth:0, 1, 0, CN:2, VN:2, Const: 43 48, dGr, W, t, DS:1 1, GT:0, V, nSt
Cir, Mth:1, 0, 0, CN:2, VN:2, Const: 3 43
Int, Mth:3, 0, 1, CN:2, VN:1, Const: 50 46
PBiss, Mth:0, 1, 0, CN:2, VN:2, Const: 51 43, dGr, W, t, DS:1 1, GT:0, V, nSt
